name: Sync job

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          debug: 'true'
    
      - name: Update submodules
        run: |
          git submodule update --remote
          git config --global user.name "Abdul Ahad Akhter"
          git config --global user.email "abdulahadakhter@outlook.com"
          git commit -am "Update submodules"
          git push

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
